<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="turtle">
<xacro:property name="yaml_file" value="$(find turtle_brick)/turtle.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}" />
<xacro:property name="start" value="${props['/**']}"/>
<xacro:property name="ros__parameters" value="${start['ros__parameters']}"/>
<xacro:property name="platform_height" value="${ros__parameters['platform_height']}"/>
<xacro:property name="wheel_radius" value="${ros__parameters['wheel_radius']}"/>
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.4 0.4 0.4"/>
      </geometry>
    </visual>
  </link>

  <link name="offset">
    <visual>
      <geometry>
        <cylinder length="${platform_height - 0.05 - 0.2  - 0.4 - wheel_radius}" radius="0.05"/>
      </geometry>
    </visual>
  </link>

  <link name="platform">
    <visual>
      <geometry>
        <box size="0.8 0.8 0.05"/>
      </geometry>
    </visual>
  </link>

  <link name="stem">
    <visual>
      <geometry>
        <cylinder length="0.2" radius="0.05"/>
      </geometry>
    </visual>
  </link>

  <link name="wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 -1.57075 0"/>
    </visual>
  </link>

  <joint name="base_to_offset" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0.5"/>
    <parent link="base_link"/>
    <child link="offset"/>
  </joint>

  <joint name="offset_to_platform" type="continuous">
    <axis xyz="1 0 0"/>
    <origin rpy="0 0 0" xyz="0 0 0.325"/>
    <parent link="offset"/>
    <child link="platform"/>
  </joint>

  <joint name="base_to_stem" type="continuous">
    <axis xyz="0 0 -1"/>
    <origin rpy="0 0 0" xyz="0 0 -0.3"/>
    <parent link="base_link"/>
    <child link="stem"/>
  </joint>

  <joint name="stem_to_wheel" type="continuous">
    <axis xyz="1 0 0"/>
    <origin xyz="0 0 -0.4"/>
    <parent link="stem"/>
    <child link="wheel"/>
  </joint>
  
</robot>